apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx
  namespace: default
data:
  enable-cors: "true"
  cors-allow-origin: "*"
---
# Ingress para rotear tr√°fego
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notas-max-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: notas-max.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nodeport
                port:
                  number: 5173
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-nodeport
                port:
                  number: 5000
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nodeport
                port:
                  number: 5173
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-nodeport
                port:
                  number: 5000
